--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31.07.2019 19:11:43
-- Server version: 8.0.16
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE ApplicationServer;

--
-- Drop table `microcontrollers`
--
DROP TABLE IF EXISTS microcontrollers;

--
-- Drop table `session_tokens`
--
DROP TABLE IF EXISTS session_tokens;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE ApplicationServer;

--
-- Create table `users`
--
CREATE TABLE users (
  Username varchar(255) NOT NULL,
  Password varchar(255) NOT NULL,
  FirstName varchar(50) DEFAULT NULL,
  LastName varchar(255) DEFAULT NULL,
  Created timestamp NOT NULL,
  `E-Mail` varchar(255) DEFAULT NULL,
  PRIMARY KEY (Username)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `Username` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX Username (Username);

--
-- Create table `session_tokens`
--
CREATE TABLE session_tokens (
  Token varchar(255) NOT NULL,
  FK_User varchar(255) NOT NULL,
  Created timestamp NOT NULL,
  Address varchar(255) NOT NULL,
  PRIMARY KEY (Token)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 744,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE session_tokens
ADD CONSTRAINT FK_session_tokens_users_Username FOREIGN KEY (FK_User)
REFERENCES users (Username) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `microcontrollers`
--
CREATE TABLE microcontrollers (
  ControllerID varchar(32) NOT NULL,
  FK_User varchar(255) NOT NULL,
  Address varchar(255) NOT NULL,
  Name varchar(50) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE microcontrollers
ADD CONSTRAINT FK_microcontrollers_users_Username FOREIGN KEY (FK_User)
REFERENCES users (Username) ON DELETE CASCADE ON UPDATE CASCADE;

-- 
-- Dumping data for table users
--
-- Table ApplicationServer.users does not contain any data (it is empty)

-- 
-- Dumping data for table session_tokens
--
-- Table ApplicationServer.session_tokens does not contain any data (it is empty)

-- 
-- Dumping data for table microcontrollers
--
-- Table ApplicationServer.microcontrollers does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;